configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjJjMjE3YWJlOGFlZjBjODViMmRhZjE3ZGIzOGViMTIwNjBhZTdhMWEzOTA0YjM3ZDE5Njc5NTIwZjhjOWFlZTdjMjcyMzk1MDg1ZWIzY2FkYWI2N2M2YWZiYTkzN2EzYWZhNTczMjdmNzAxNzI3ODhkMDcwMzgwZjZkY2I3MGU=
