package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClinicalCaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseAllPropertiesEquals(ClinicalCase expected, ClinicalCase actual) {
        assertClinicalCaseAutoGeneratedPropertiesEquals(expected, actual);
        assertClinicalCaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseAllUpdatablePropertiesEquals(ClinicalCase expected, ClinicalCase actual) {
        assertClinicalCaseUpdatableFieldsEquals(expected, actual);
        assertClinicalCaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseAutoGeneratedPropertiesEquals(ClinicalCase expected, ClinicalCase actual) {
        assertThat(actual)
            .as("Verify ClinicalCase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseUpdatableFieldsEquals(ClinicalCase expected, ClinicalCase actual) {
        assertThat(actual)
            .as("Verify ClinicalCase relevant properties")
            .satisfies(a -> assertThat(a.getPatientId()).as("check patientId").isEqualTo(expected.getPatientId()))
            .satisfies(a -> assertThat(a.getOpenedAt()).as("check openedAt").isEqualTo(expected.getOpenedAt()))
            .satisfies(a -> assertThat(a.getBrief()).as("check brief").isEqualTo(expected.getBrief()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getSymptoms()).as("check symptoms").isEqualTo(expected.getSymptoms()))
            .satisfies(a -> assertThat(a.getDiagnosis()).as("check diagnosis").isEqualTo(expected.getDiagnosis()))
            .satisfies(a ->
                assertThat(a.getAssignedProfessionalId()).as("check assignedProfessionalId").isEqualTo(expected.getAssignedProfessionalId())
            )
            .satisfies(a -> assertThat(a.getAssignedRosterId()).as("check assignedRosterId").isEqualTo(expected.getAssignedRosterId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseUpdatableRelationshipsEquals(ClinicalCase expected, ClinicalCase actual) {
        assertThat(actual)
            .as("Verify ClinicalCase relationships")
            .satisfies(a -> assertThat(a.getRecommendations()).as("check recommendations").isEqualTo(expected.getRecommendations()));
    }
}
