package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClinicalCaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseAllPropertiesEquals(ClinicalCase expected, ClinicalCase actual) {
        assertClinicalCaseAutoGeneratedPropertiesEquals(expected, actual);
        assertClinicalCaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseAllUpdatablePropertiesEquals(ClinicalCase expected, ClinicalCase actual) {
        assertClinicalCaseUpdatableFieldsEquals(expected, actual);
        assertClinicalCaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseAutoGeneratedPropertiesEquals(ClinicalCase expected, ClinicalCase actual) {
        assertThat(actual)
            .as("Verify ClinicalCase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseUpdatableFieldsEquals(ClinicalCase expected, ClinicalCase actual) {
        assertThat(actual)
            .as("Verify ClinicalCase relevant properties")
            .satisfies(a -> assertThat(a.getSymptoms()).as("check symptoms").isEqualTo(expected.getSymptoms()))
            .satisfies(a -> assertThat(a.getDiagnoses()).as("check diagnoses").isEqualTo(expected.getDiagnoses()))
            .satisfies(a -> assertThat(a.getRecommendations()).as("check recommendations").isEqualTo(expected.getRecommendations()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getOpenDate()).as("check openDate").isEqualTo(expected.getOpenDate()))
            .satisfies(a -> assertThat(a.getCloseDate()).as("check closeDate").isEqualTo(expected.getCloseDate()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClinicalCaseUpdatableRelationshipsEquals(ClinicalCase expected, ClinicalCase actual) {
        // empty method
    }
}
