package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DutyRosterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDutyRosterAllPropertiesEquals(DutyRoster expected, DutyRoster actual) {
        assertDutyRosterAutoGeneratedPropertiesEquals(expected, actual);
        assertDutyRosterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDutyRosterAllUpdatablePropertiesEquals(DutyRoster expected, DutyRoster actual) {
        assertDutyRosterUpdatableFieldsEquals(expected, actual);
        assertDutyRosterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDutyRosterAutoGeneratedPropertiesEquals(DutyRoster expected, DutyRoster actual) {
        assertThat(actual)
            .as("Verify DutyRoster auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDutyRosterUpdatableFieldsEquals(DutyRoster expected, DutyRoster actual) {
        assertThat(actual)
            .as("Verify DutyRoster relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a ->
                assertThat(a.getSubscribedProfessionalIds())
                    .as("check subscribedProfessionalIds")
                    .isEqualTo(expected.getSubscribedProfessionalIds())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDutyRosterUpdatableRelationshipsEquals(DutyRoster expected, DutyRoster actual) {
        // empty method
    }
}
