package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCCredentialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCCredentialAllPropertiesEquals(HCCredential expected, HCCredential actual) {
        assertHCCredentialAutoGeneratedPropertiesEquals(expected, actual);
        assertHCCredentialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCCredentialAllUpdatablePropertiesEquals(HCCredential expected, HCCredential actual) {
        assertHCCredentialUpdatableFieldsEquals(expected, actual);
        assertHCCredentialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCCredentialAutoGeneratedPropertiesEquals(HCCredential expected, HCCredential actual) {
        assertThat(actual)
            .as("Verify HCCredential auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCCredentialUpdatableFieldsEquals(HCCredential expected, HCCredential actual) {
        assertThat(actual)
            .as("Verify HCCredential relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getPassword()).as("check password").isEqualTo(expected.getPassword()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCCredentialUpdatableRelationshipsEquals(HCCredential expected, HCCredential actual) {
        // empty method
    }
}
