package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentAllPropertiesEquals(HCDocument expected, HCDocument actual) {
        assertHCDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertHCDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentAllUpdatablePropertiesEquals(HCDocument expected, HCDocument actual) {
        assertHCDocumentUpdatableFieldsEquals(expected, actual);
        assertHCDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentAutoGeneratedPropertiesEquals(HCDocument expected, HCDocument actual) {
        assertThat(actual)
            .as("Verify HCDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentUpdatableFieldsEquals(HCDocument expected, HCDocument actual) {
        assertThat(actual)
            .as("Verify HCDocument relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCDocumentUpdatableRelationshipsEquals(HCDocument expected, HCDocument actual) {
        // empty method
    }
}
