package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCPayOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionAllPropertiesEquals(HCPayOption expected, HCPayOption actual) {
        assertHCPayOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertHCPayOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionAllUpdatablePropertiesEquals(HCPayOption expected, HCPayOption actual) {
        assertHCPayOptionUpdatableFieldsEquals(expected, actual);
        assertHCPayOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionAutoGeneratedPropertiesEquals(HCPayOption expected, HCPayOption actual) {
        assertThat(actual)
            .as("Verify HCPayOption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionUpdatableFieldsEquals(HCPayOption expected, HCPayOption actual) {
        assertThat(actual)
            .as("Verify HCPayOption relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getUserID()).as("check userID").isEqualTo(expected.getUserID()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCPayOptionUpdatableRelationshipsEquals(HCPayOption expected, HCPayOption actual) {
        // empty method
    }
}
