package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedCaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedCaseAllPropertiesEquals(MedCase expected, MedCase actual) {
        assertMedCaseAutoGeneratedPropertiesEquals(expected, actual);
        assertMedCaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedCaseAllUpdatablePropertiesEquals(MedCase expected, MedCase actual) {
        assertMedCaseUpdatableFieldsEquals(expected, actual);
        assertMedCaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedCaseAutoGeneratedPropertiesEquals(MedCase expected, MedCase actual) {
        assertThat(actual)
            .as("Verify MedCase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedCaseUpdatableFieldsEquals(MedCase expected, MedCase actual) {
        assertThat(actual)
            .as("Verify MedCase relevant properties")
            .satisfies(a -> assertThat(a.getSymptoms()).as("check symptoms").isEqualTo(expected.getSymptoms()))
            .satisfies(a -> assertThat(a.getDiagnoses()).as("check diagnoses").isEqualTo(expected.getDiagnoses()))
            .satisfies(a -> assertThat(a.getRecommendations()).as("check recommendations").isEqualTo(expected.getRecommendations()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedCaseUpdatableRelationshipsEquals(MedCase expected, MedCase actual) {
        // empty method
    }
}
