package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecommendationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAllPropertiesEquals(Recommendation expected, Recommendation actual) {
        assertRecommendationAutoGeneratedPropertiesEquals(expected, actual);
        assertRecommendationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAllUpdatablePropertiesEquals(Recommendation expected, Recommendation actual) {
        assertRecommendationUpdatableFieldsEquals(expected, actual);
        assertRecommendationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAutoGeneratedPropertiesEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationUpdatableFieldsEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationUpdatableRelationshipsEquals(Recommendation expected, Recommendation actual) {
        // The inverse side of the many-to-many is not serialized back, so there is nothing to compare here.
    }
}
