package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShiftAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAllPropertiesEquals(Shift expected, Shift actual) {
        assertShiftAutoGeneratedPropertiesEquals(expected, actual);
        assertShiftAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAllUpdatablePropertiesEquals(Shift expected, Shift actual) {
        assertShiftUpdatableFieldsEquals(expected, actual);
        assertShiftUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAutoGeneratedPropertiesEquals(Shift expected, Shift actual) {
        assertThat(actual)
            .as("Verify Shift auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftUpdatableFieldsEquals(Shift expected, Shift actual) {
        assertThat(actual)
            .as("Verify Shift relevant properties")
            .satisfies(a -> assertThat(a.getRosterId()).as("check rosterId").isEqualTo(expected.getRosterId()))
            .satisfies(a -> assertThat(a.getProfessionalId()).as("check professionalId").isEqualTo(expected.getProfessionalId()))
            .satisfies(a -> assertThat(a.getStartsAt()).as("check startsAt").isEqualTo(expected.getStartsAt()))
            .satisfies(a -> assertThat(a.getEndsAt()).as("check endsAt").isEqualTo(expected.getEndsAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftUpdatableRelationshipsEquals(Shift expected, Shift actual) {
        // empty method
    }
}
